// <auto-generated />
namespace AltranSIWallet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddEntities_Consultant_Manager_Project_ProjectManager_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEntities_Consultant_Manager_Project_ProjectManager_User));
        
        string IMigrationMetadata.Id
        {
            get { return "202010070823460_AddEntities_Consultant_Manager_Project_ProjectManager_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
